#' Pharmacological action on targeted DEGs
#'
#' Used for manual evaluation of pharmacological counteraction of DEG fold change
#'
#' @param drug_dist_files Vector with complete filepaths to the average closest network distance files (generated by `average_closest_distance_network_drug_screening()`) for which the pharmacological action on targeted DEGs shall be summarized
#' @param deg_files Vector with the same length drug_dist_files with complete filepaths to the DEG files (generated by `calculate_DEGs()` in this example). Every element in `deg_files` is matched with the corresponding element in `drug_dist_files`.
#' @param pharma_effect Matrix with three columns, in which the first column specifies the drug identifier matchable with the first column in the average closest netwrok distance files. The second column specifies the drug target and column three specifies the pharmacological action on the drug target.
#' @param save_names Vector specifying the names for output. Each file corresponds to the processed version of a `drug_dist_files`.
#' @param out_dir Character string, indicating the directory in which output shall be saved.
#' @param cores Integer specifying the number of cores to be used in computation.
#'
#' @export
#'
pharma_effect_on_fold_change <- function(drug_dist_files, deg_files, pharma_effect, save_names, out_dir = "", cores = 1){

  # check if package is available
  if (!requireNamespace("doParallel", quietly = TRUE)) {
    stop(
      "Package \'doParallel\' must be installed to use this function",
      call. = FALSE
    )
  }
  library(doParallel)
  if(cores > 1) {
    registerDoParallel(cores = cores)
  }

  # Check if input is correct
  if(length(drug_dist_files) != length(deg_files)) {
    stop("'drug_dist_files' and 'deg_files' do specify a different amount of files!", call. = FALSE)
  }
  if(ncol(pharma_effect) != 3) {
    stop("'pharma_effect' is supposed to be a matrix with 3 colums!", call. = FALSE)
  }
  if(out_dir != ""){
    if(substr(x = out_dir, start = nchar(out_dir), stop = nchar(out_dir)) != "/"){
      out_dir <- paste(out_dir, "/",sep="")
    }
  }

  # START CODE

  for(cl in 1:length(deg_files)){
    dist <- read.table(file = drug_dist_files[cl], sep ="\t", header = T)
    if(is.null(dist)){
      stop(paste("'drug_dist_files[", cl, "]' is NULL when trying to load", sep =""))
    }
    deg <- read.table(file = deg_files[cl], sep = "\t", header = T)
    if(is.null(dist)){
      stop(paste("'deg_files[", cl, "]' is NULL when trying to load", sep =""))
    }
    # fold change to "up" and "down"
    deg[as.numeric(deg[,3])>0,2] <- "up"
    deg[as.numeric(deg[,3])<0,2] <- "down"
    deg <- deg[,1:2]

    out <- foreach(i = c(1:nrow(dist)), .combine = "rbind") %dopar% {
      drug <- pharma_effect[pharma_effect[,1] %in% dist[i,1],2:3]
      if(is.null(nrow(drug))){
        drug <- matrix(drug, nrow = 1)
      }
      n_targets <- nrow(drug)
      target_out <- paste(paste(drug[,1], " (", drug[,2],")", sep = ""), collapse = ", ")
      n_targeted_degs <- sum(!is.na(deg[match(as.character(drug[,1]), as.character(deg[,1])),2]))

      if(n_targeted_degs > 1){
        drug <- drug[drug[,1] %in% deg[,1],]
        deg_out <- paste(paste(drug[,1], " (", deg[match(as.character(drug[,1]), as.character(deg[,1])),2],")", sep = ""), collapse = ", ")
      } else {
        drug <- drug[drug[,1] %in% deg[,1],1]
        deg_out <- paste(drug, " (", deg[match(as.character(drug), as.character(deg[,1])),2],")", sep = "")
      }
      return(c(n_targets = n_targets, n_targeted_degs = n_targeted_degs, targeted_degs = deg_out, pharmacological_effect = target_out))
    }
    out <- cbind(dist, out)
    write.table(out, file = paste(out_dir, save_names[cl], ".txt",sep=""), sep = "\t", col.names = T, row.names = F)
  }
  out <- combine_evaluation_files(files = paste(out_dir, save_names, ".txt",sep=""),
                           label_for_files = save_names,
                           output_file_name = paste(out_dir, "SUMMARY_FC_criterion_evaluation.txt", sep=""),
                           cores = 1)
  out <- out[order(out[,1]),]
  return(out)
}
